### ISSUE TITLE
Cannot access dashboard and billing pages

### ISSUE THREAD

**Issue by logancyang** [saasfly/saasfly#113]
Hi, thanks for making the template. I have set up the dev env with a Vercel postgres db. The landing page, sign up and sign in via github, dashboard/billing/setting pages all work locally.

But after I deploy to Vercel and added all the env variables there, dashboard and billing page don't work after sign in. Seems related the tRPC calls not authorized. The github oauth seems to be working fine since the setting page is working. 

Any help is appreciated!

```
u [TRPCClientError]: UNAUTHORIZED
    at u.from (/var/task/apps/nextjs/.next/server/chunks/6527.js:2:25690)
    at /var/task/apps/nextjs/.next/server/chunks/6527.js:2:29586
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  meta: {
    response: Response {
      status: 401,
      statusText: 'Unauthorized',
      headers: Headers {
        age: '0',
        'cache-control': 'public, max-age=0, must-revalidate',
        'content-type': 'application/json',
        date: 'Fri, 20 Sep 2024 22:30:25 GMT',
        server: 'Vercel',
        'strict-transport-security': 'max-age=63072000',
        vary: 'RSC, Next-Router-State-Tree, Next-Router-Prefetch',
        'x-matched-path': '/api/trpc/edge/[trpc]',
        'x-vercel-cache': 'MISS',
        'x-vercel-id': 'pdx1:iad1::iad1::c26ft-1726871425517-a2f0a9cd6189',
        'transfer-encoding': 'chunked'
      },
      body: ReadableStream { locked: true, state: 'closed', supportsBYOB: true },
      bodyUsed: true,
      ok: false,
      redirected: true,
      type: 'cors',
      url: 'https://www.obsidiancopilot.com/api/trpc/edge/customer.queryCustomer?batch=1&input=%7B%220%22%3A%7B%22json%22%3A%7B%22userId%22%3A%22a2ec4411-6dae-4c76-8ba4-604d4b878421%22%7D%7D%7D'
    },
    responseJSON: [ [Object] ]
  },
  shape: {
    message: 'UNAUTHORIZED',
    code: -32001,
    data: {
      code: 'UNAUTHORIZED',
      httpStatus: 401,
      path: 'customer.queryCustomer',
      zodError: null
    }
  },
  data: {
    code: 'UNAUTHORIZED',
    httpStatus: 401,
    path: 'customer.queryCustomer',
    zodError: null
  },
  digest: '2488828857',
  [cause]: undefined
}
```

**Comment by logancyang** [comment]
> It seems like you're using CORS with the option type: 'cors'.

Not sure where this is set, I didn't do anything. And yes the two are identical:

<img width="612" alt="SCR-20240920-pxqv" src="https://github.com/user-attachments/assets/772351d8-f414-4124-a8ea-c21fd7cf7501">
<img width="593" alt="SCR-20240920-pxxc" src="https://github.com/user-attachments/assets/7f62f27d-fe8d-40cd-b917-24994e17187b">

**Comment by logancyang** [comment]
Ok, setting them both to `www.obsidiancopilot.com` solved the issue.
