### ISSUE TITLE
build error 

### ISSUE THREAD

**Issue by anhao** [saasfly/saasfly#4]
> Build error occurred
Error: Failed to collect page data for /api/webhooks/stripe
@saasfly/nextjs:build:     at /workspace/saasfly/node_modules/next/dist/build/utils.js:1217:15
@saasfly/nextjs:build:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
@saasfly/nextjs:build:   type: 'Error'
@saasfly/nextjs:build: }
@saasfly/nextjs:build:    Collecting page data  .error: script "with-env" exited with code 1
@saasfly/nextjs:build: error: script "build" exited with code 1
@saasfly/nextjs:build: ERROR: command finished with error: command (/workspace/saasfly/apps/nextjs) /home/gitpod/.nvm/versions/node/v20.11.1/bin/bun run build exited (1)
@saasfly/nextjs#build: command (/workspace/saasfly/apps/nextjs) /home/gitpod/.nvm/versions/node/v20.11.1/bin/bun run build exited (1)

 Tasks:    0 successful, 1 total
Cached:    0 cached, 1 total
  Time:    30.853s 
Failed:    @saasfly/nextjs#build

 ERROR  run failed: command  exited (1)
error: script "build" exited with code 1

**Comment by anhao** [comment]
$ turbo build

Attention:
Turborepo now collects completely anonymous telemetry regarding usage.
This information is used to shape the Turborepo roadmap and prioritize features.
You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
https://turbo.build/repo/docs/telemetry

• Packages in scope: @saasfly/api, @saasfly/auth, @saasfly/common, @saasfly/db, @saasfly/eslint-config, @saasfly/nextjs, @saasfly/prettier-config, @saasfly/stripe, @saasfly/tailwind-config, @saasfly/typescript-config, @saasfly/ui
• Running build in 11 packages
• Remote caching disabled
@saasfly/nextjs:build: cache miss, executing 0e49b66d8d95d811
@saasfly/nextjs:build: $ contentlayer build && bun with-env next build
@saasfly/nextjs:build: Generated 9 documents in .contentlayer
@saasfly/nextjs:build: TypeError: The "code" argument must be of type number. Received an instance of Object
@saasfly/nextjs:build:     at process.set [as exitCode] (node:internal/bootstrap/node:123:9)
@saasfly/nextjs:build:     at Cli.runExit (/workspace/saasfly/node_modules/clipanion/lib/advanced/Cli.js:232:26)
@saasfly/nextjs:build:     at run (file:///workspace/saasfly/node_modules/@contentlayer/cli/src/index.ts:39:3)
@saasfly/nextjs:build:     at main (/workspace/saasfly/node_modules/contentlayer/bin/cli.cjs:5:3) {
@saasfly/nextjs:build:   code: 'ERR_INVALID_ARG_TYPE'
@saasfly/nextjs:build: }
@saasfly/nextjs:build: $ dotenv -e ../../.env.local -- next build
@saasfly/nextjs:build: Attention: Next.js now collects completely anonymous telemetry regarding usage.
@saasfly/nextjs:build: This information is used to shape Next.js' roadmap and prioritize features.
@saasfly/nextjs:build: You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
@saasfly/nextjs:build: https://nextjs.org/telemetry
@saasfly/nextjs:build: 
@saasfly/nextjs:build:    ▲ Next.js 14.0.3
@saasfly/nextjs:build: 
@saasfly/nextjs:build:  ✓ Creating an optimized production build 
@saasfly/nextjs:build:  ✓ Compiled successfully
@saasfly/nextjs:build:    Skipping validation of types
@saasfly/nextjs:build:    Skipping linting
   Collecting page data  .sa [VercelPostgresError]: VercelPostgresError - 'invalid_connection_string': This connection string is meant to be used with a direct connection. Make sure to use a pooled connection string or try `createClient()` instead.
@saasfly/nextjs:build:     at su (/workspace/saasfly/apps/nextjs/.next/server/chunks/406.js:18:5468)
@saasfly/nextjs:build:     at sg (/workspace/saasfly/apps/nextjs/.next/server/chunks/406.js:18:7411)
@saasfly/nextjs:build:     at 15491 (/workspace/saasfly/apps/nextjs/.next/server/app/api/webhooks/stripe/route.js:1:13590)
@saasfly/nextjs:build:     at t (/workspace/saasfly/apps/nextjs/.next/server/webpack-runtime.js:1:128)
@saasfly/nextjs:build:     at 36577 (/workspace/saasfly/apps/nextjs/.next/server/app/api/webhooks/stripe/route.js:1:14481)
@saasfly/nextjs:build:     at t (/workspace/saasfly/apps/nextjs/.next/server/webpack-runtime.js:1:128)
@saasfly/nextjs:build:     at 82870 (/workspace/saasfly/apps/nextjs/.next/server/app/api/webhooks/stripe/route.js:1:1028)
@saasfly/nextjs:build:     at t (/workspace/saasfly/apps/nextjs/.next/server/webpack-runtime.js:1:128)
@saasfly/nextjs:build:     at r (/workspace/saasfly/apps/nextjs/.next/server/app/api/webhooks/stripe/route.js:1:17587)
@saasfly/nextjs:build:     at /workspace/saasfly/apps/nextjs/.next/server/app/api/webhooks/stripe/route.js:1:17622 {
@saasfly/nextjs:build:   code: 'invalid_connection_string'
@saasfly/nextjs:build: }

> Build error occurred
Error: Failed to collect page data for /api/webhooks/stripe
@saasfly/nextjs:build:     at /workspace/saasfly/node_modules/next/dist/build/utils.js:1217:15
@saasfly/nextjs:build:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
@saasfly/nextjs:build:   type: 'Error'
@saasfly/nextjs:build: }
@saasfly/nextjs:build:    Collecting page data  .error: script "with-env" exited with code 1
@saasfly/nextjs:build: error: script "build" exited with code 1
@saasfly/nextjs:build: ERROR: command finished with error: command (/workspace/saasfly/apps/nextjs) /home/gitpod/.nvm/versions/node/v20.11.1/bin/bun run build exited (1)
@saasfly/nextjs#build: command (/workspace/saasfly/apps/nextjs) /home/gitpod/.nvm/versions/node/v20.11.1/bin/bun run build exited (1)

 Tasks:    0 successful, 1 total
Cached:    0 cached, 1 total
  Time:    11.494s 
Failed:    @saasfly/nextjs#build

 ERROR  run failed: command  exited (1)
error: script "build" exited with code 1


env:

```
# -----------------------------------------------------------------------------
# App
# -----------------------------------------------------------------------------
NEXT_PUBLIC_APP_URL='localhost:3000'
# -----------------------------------------------------------------------------
# Authentication (NextAuth.js)
# openssl rand -base64 32
# -----------------------------------------------------------------------------
NEXTAUTH_URL='localhost:3000'
NEXTAUTH_SECRET='1'

GITHUB_CLIENT_ID='1'
GITHUB_CLIENT_SECRET='1'

# -----------------------------------------------------------------------------
# Email (RESEND)
# -----------------------------------------------------------------------------
RESEND_API_KEY='1'
RESEND_FROM='1'

# -----------------------------------------------------------------------------
# Subscriptions (Stripe)
# -----------------------------------------------------------------------------
# Stripe
STRIPE_API_KEY="1"
STRIPE_WEBHOOK_SECRET="1"
NEXT_PUBLIC_STRIPE_STD_PRODUCT_ID="prod_"
NEXT_PUBLIC_STRIPE_STD_MONTHLY_PRICE_ID="price_"
NEXT_PUBLIC_STRIPE_PRO_PRODUCT_ID="prod_"
NEXT_PUBLIC_STRIPE_PRO_MONTHLY_PRICE_ID="price_"

NEXT_PUBLIC_STRIPE_PRO_PRODUCT_ID="prod_"
NEXT_PUBLIC_STRIPE_PRO_MONTHLY_PRICE_ID="price_"
NEXT_PUBLIC_STRIPE_PRO_YEARLY_PRICE_ID="price_"
NEXT_PUBLIC_STRIPE_BUSINESS_PRODUCT_ID="prod_"
NEXT_PUBLIC_STRIPE_BUSINESS_MONTHLY_PRICE_ID="price_"
NEXT_PUBLIC_STRIPE_BUSINESS_YEARLY_PRICE_ID="price_"

#posthog
NEXT_PUBLIC_POSTHOG_KEY=" "
NEXT_PUBLIC_POSTHOG_HOST=https://app.posthog.com

POSTGRES_URL="postgres://default:4uFqHEDMIOv1@ep-little-snow-a4ah3csq.us-east-1.aws.neon.tech:5432/verceldb?sslmode=require"



```

**Comment by anhao** [comment]
Think , The build was successful.
