### ISSUE TITLE
/dashboard, /docs and other pages doesn't work

### ISSUE THREAD

**Issue by alexandrosk** [saasfly/saasfly#79]
I can only see the homepage and login, everything else fails 

```
GET /en/dashboard 200 in 629ms
@saasfly/nextjs:dev:  ⨯ ../../node_modules/@trpc/client/dist/TRPCClientError.mjs (40:1) @ TRPCClientError.from
@saasfly/nextjs:dev:  ⨯ Internal error: TRPCClientError: fetch failed
@saasfly/nextjs:dev:     at TRPCClientError.from (../../node_modules/@trpc/client/dist/TRPCClientError.mjs:45:16)
@saasfly/nextjs:dev:     at eval (../../node_modules/@trpc/client/dist/links/httpBatchLink.mjs:100:102)
@saasfly/nextjs:dev: digest: "1404646353"
@saasfly/nextjs:dev: Cause: TypeError: fetch failed
```

`⨯ Error: Dynamic server usage: Page with `dynamic = "force-dynamic"` won't be rendered statically.`

**Comment by AbdelfattahSekak** [comment]
I have the same error, I suspect it is because of the unstable functions `experimental_createTRPCNextAppDirClient` and   `experimental_createTRPCNextAppDirServer` imported from `@trpc/next`
